class UniversityAdmissionBot:
    ...
    def get_admission_info(self, country, university, degree, major):
        ...
        # Change this line to call the correct method
        language_requirements = self._get_basic_requirements()  # Updated line
        ... 